/**
 * 数据结构与算法
 */
export const webAlgorithm = {
  目录: ["/algorithm/README.md"],
  复杂度分析: [
    "/algorithm/basic/时间复杂度.md",
    "/algorithm/basic/空间复杂度.md",
  ],
  算法思想: ["/algorithm/basic/基本算法思想.md"],
  算法技巧: ["/algorithm/basic/基本算法技巧.md"],
  数据结构: [
    "/algorithm/dataStructure/数组.md",
    "/algorithm/dataStructure/栈.md",
    "/algorithm/dataStructure/队列.md",
    "/algorithm/dataStructure/队列-循环队列.md",
    "/algorithm/dataStructure/队列-优先队列.md",
    "/algorithm/dataStructure/队列-阻塞队列.md",
    "/algorithm/dataStructure/队列-并发队列.md",
    "/algorithm/dataStructure/链表.md",
    "/algorithm/dataStructure/链表-双向链表.md",
    "/algorithm/dataStructure/链表-循环链表.md",
    "/algorithm/dataStructure/链表-跳跃表.md",
    "/algorithm/dataStructure/树.md",
    "/algorithm/dataStructure/树-平衡树.md",
    "/algorithm/dataStructure/树-红黑树.md",
    "/algorithm/dataStructure/树-B+树.md",
    "/algorithm/dataStructure/树-B-树.md",
    "/algorithm/dataStructure/堆栈.md",
    "/algorithm/dataStructure/图.md",
  ],
  排序算法: [
    "/algorithm/sort/冒泡排序.md",
    "/algorithm/sort/快速排序.md",
    "/algorithm/sort/插入排序.md",
    "/algorithm/sort/希尔排序.md",
    "/algorithm/sort/选择排序.md",
    "/algorithm/sort/归并排序.md",
    "/algorithm/sort/计数排序.md",
    "/algorithm/sort/基数排序.md",
    "/algorithm/sort/堆排序.md",
    "/algorithm/sort/桶排序.md",
  ],
  搜索算法: ["/algorithm/search/二分查找.md"],
  其它算法: [
    "/algorithm/other/摇树算法.md",
    "/algorithm/other/结构化克隆算法.md",
    "/algorithm/other/LRU缓存淘汰算法.md",
    "/algorithm/other/DIFF.md",
    "/algorithm/other/Nagle.md",
  ],
};
