/**
 * 设计模式
 */
export const webPattern = {
  基础: ["/pattern/basic/面向对象基础.md"],
  创建型: [
    "/pattern/create/工厂模式Factory.md",
    "/pattern/create/抽象工厂模式AbstractFactory.md",
    "/pattern/create/建造者模式Builder.md",
    "/pattern/create/原型模式Prototype.md",
    "/pattern/create/单例模式Singleton.md",
  ],
  结构型: [
    "/pattern/structure/适配器模式Adapter.md",
    "/pattern/structure/桥接模式Bridge.md",
    "/pattern/structure/组合模式Composite.md",
    "/pattern/structure/装饰者模式Decorator.md",
    "/pattern/structure/外观模式Facade.md",
    "/pattern/structure/亨元模式Flyweight.md",
    "/pattern/structure/代理模式Proxy.md",
  ],
  行为型: [
    "/pattern/behavior/命令模式Command.md",
    "/pattern/behavior/职责链模式ChainOfResponsibility.md",
    "/pattern/behavior/解释器模式Interpreter.md",
    "/pattern/behavior/迭代器模式Iterator.md",
    "/pattern/behavior/中介者模式Mediator.md",
    "/pattern/behavior/备忘录模式Memento.md",
    "/pattern/behavior/观察者模式Observer.md",
    "/pattern/behavior/简单模板模式SimplateTemplate.md",
    "/pattern/behavior/状态模式State.md",
    "/pattern/behavior/策略模式Strategy.md",
    "/pattern/behavior/模板方法模式TemplateMethod.md",
    "/pattern/behavior/访问者模式Visitor.md",
  ],
  技巧型: [
    "/pattern/skill/函数柯里化Curry.md",
    "/pattern/skill/数据访问对象模式DAO.md",
    "/pattern/skill/委托模式Entrust.md",
    "/pattern/skill/惰性模式Layier.md",
    "/pattern/skill/链模式OperateOfResponsibility.md",
    "/pattern/skill/参与者模式Participator.md",
    "/pattern/skill/等待者模式Waitor.md",
    "/pattern/skill/节流模式Throttler.md",
  ],
  架构型: [
    "/pattern/framework/MVC.md",
    "/pattern/framework/MVP.md",
    "/pattern/framework/MVVM.md",
    "/pattern/framework/SMD.md",
    "/pattern/framework/AMD.md",
    "/pattern/framework/Widget.md",
  ],
  其它: ["/pattern/other/DI.md", "/pattern/other/IoC.md"],
};
